server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testDb
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
