<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://www.intership.ttsw.com.pl/soap-six-warehouse"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/"
             targetNamespace="http://www.intership.ttsw.com.pl/soap-six-warehouse"
             name="SixWarehouseEndpointService">
    <types>
        <xsd:schema>
            <xsd:import namespace="http://www.intership.ttsw.com.pl/soap-six-warehouse"
                        schemaLocation="../xsd/six-warehouse.xsd"/>
        </xsd:schema>
    </types>
    <message name="getAllProducts">
        <part name="parameters" element="tns:getAllProducts"/>
    </message>
    <message name="getAllProductsResponse">
        <part name="parameters" element="tns:getAllProductsResponse"/>
    </message>
    <portType name="SixWarehouseEndpoint">
        <operation name="getAllProducts">
            <input message="tns:getAllProducts"/>
            <output message="tns:getAllProductsResponse"/>
        </operation>
    </portType>
    <binding name="SixWarehouseEndpointPortBinding" type="tns:SixWarehouseEndpoint">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="getAllProducts">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="SixWarehouseEndpointService">
        <port name="SixWarehouseEndpointPort" binding="tns:SixWarehouseEndpointPortBinding">
            <soap:address location="http://localhost:8080/soap-service"/>
        </port>
    </service>
</definitions>